name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cli/gh-extension-precompile@v2
        with:
          go_version_file: go.mod

      - name: Installation test after precompilation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh extension install thombashi/gh-actionarmor
